# Generated by Django 6.0 on 2026-01-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
