# Generated by Django 6.0 on 2026-01-01 10:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_alter_affiliate_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='referral_code',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['referral_code'], name='affiliates__referra_539307_idx'),
        ),
    ]
