# Generated by Django 6.0 on 2026-01-01 08:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Affiliate commission percentage for this product', max_digits=5),
        ),
    ]
